name: Pull Request Workflow
# This workflow will be triggered on pull request events
on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tedrisat-test
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
      
      - name: Audit dependencies
        run: npm run security-check

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test:coverage

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          multiple-files: |
            Tedrisat, ./apps/tedrisat/coverage/coverage-summary.json
            Teskilat, ./apps/teskilat/coverage/coverage-summary.json
          multiple-junitxml-files: |
            Tedrisat, ./apps/tedrisat/coverage/junit.xml
            Teskilat, ./apps/teskilat/coverage/junit.xml

      - name: Build application
        run: npm run build
    